services:
  web:
    image: python:3.9
    working_dir: /api-vinhos/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: >
      sh -c "
      pip install --no-cache-dir -r /app/backend/requirements.txt &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "
